FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# Install various softwares
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y \
  python-is-python3 \
  python3-dev \
  libpython3-all-dev \
  python-dev-is-python3 \
  python3-pip \
  build-essential \
  git \
  autoconf \
  libtool \
  llvm \
  vim \
  fish \
  wget \
  parallel \
  s3cmd \
  awscli \
  htop \
  wget \
  fish \
  apt-transport-https \
  ca-certificates \
  gnupg \
  curl \
  jq \
  parallel \
  tmux \
  cmake \
  gdb \
  lsof \
  ninja

# Install Google tools
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update
RUN apt-get install google-cloud-cli

# Install ROCm
RUN wget https://repo.radeon.com/amdgpu-install/5.4.3/ubuntu/jammy/amdgpu-install_5.4.50403-1_all.deb && \
    apt-get install -y ./amdgpu-install_5.4.50403-1_all.deb && \
    amdgpu-install -y --accept-eula --usecase=rocm --no-dkms && \
    rm ./amdgpu-install_5.4.50403-1_all.deb && \
    apt-get install -y rccl rocm-libs
ENV ROCM_HOME=/opt/rocm

# Install MPICH
ENV MPICH_VERSION="3.1.4"
RUN cd /opt && \
    wget https://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz && \
    tar xf mpich-${MPICH_VERSION}.tar.gz && \
    cd mpich-${MPICH_VERSION} && \
    ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr && \
    make -j install && \
    ldconfig

# Install aws-ofi-rccl
RUN apt-get install -y libfabric-dev
RUN cd /opt && \
    git clone https://github.com/ROCmSoftwarePlatform/rccl.git && \
    cd rccl && \
    mkdir build && \
    cd build/ && \
    CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_PREFIX_PATH=/opt/rocm/ .. && \
    make -j
RUN cd /opt && \
    git clone https://github.com/ROCmSoftwarePlatform/aws-ofi-rccl && \
    cd aws-ofi-rccl && \
    ./autogen.sh && \
    CC=cc ./configure --with-libfabric=/usr/lib/x86_64-linux-gnu --with-hip=/opt/rocm --with-rccl=/opt/rccl/build && \
    make -j && \
    make install && \
    ldconfig
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

# Install torch
RUN pip install --upgrade pip
RUN apt-get install -y libmkl-dev
RUN git clone --recursive -b v1.13.1 https://github.com/pytorch/pytorch &&
    cd pytorch && \
    export USE_CUDA=0 && \
    export USE_ROCM=1 && \
    python tools/amd_build/build_amd.py && \
    export CMAKE_PREFIX_PATH=$(dirname $(which cmake)) && \
    export PYTORCH_ROCM_ARCH=gfx90a && \
    python setup.py install

# Install DeepSpeed
RUN pip install --no-cache-dir mpi4py
RUN cd /opt && \
    git clone https://github.com/microsoft/DeepSpeed && \
    cd DeepSpeed && \
    ./install.sh --allow_sudo && \
    sed -i 's/hostname -I/hostname -s/g' /usr/local/lib/python3.10/dist-packages/deepspeed/comm/comm.py

# Install more dependencies
COPY requirements.txt requirements.txt
COPY examples/llm/requirements.txt llm-requirements.txt
RUN pip install --no-cache-dir -r requirements.txt -r llm-requirements.txt
RUN pip install --no-cache-dir py-spy
RUN pip install --no-cache-dir wandb --upgrade

# Cleanup
RUN apt-get autoremove
RUN rm -rf /opt/mpich-3.1.4 /opt/aws-ofi-rccl /opt/DeepSpeed /opt/pytorch
RUN apt-get clean
RUN pip cache purge
